# #003_NumPy

## np.newaxis 

In [8]:
import numpy as np

In [12]:
a = np.array([[11,22],[21,22],[31,32]])

In [13]:
a[np.newaxis]

array([[[11, 22],
        [21, 22],
        [31, 32]]])

In [14]:
a[:,np.newaxis]

array([[[11, 22]],

       [[21, 22]],

       [[31, 32]]])

In [15]:
a[:,:,np.newaxis]

array([[[11],
        [22]],

       [[21],
        [22]],

       [[31],
        [32]]])

---

In [17]:
a = np.array([1,2,3])

In [18]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.tile(a,(2,3)) # == np.tile(a,[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

---

###  외부 File 읽어오기

In [21]:
%%writefile t.csv
1,2,3
4,5,6

Writing t.csv


In [28]:
x = np.loadtxt('t.csv', delimiter=',') #delimiter ',' : NumPy가 이해할 수 있게 ,로 이뤄진 것을 알려줌
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
x = np.genfromtxt('t.csv',delimiter=',') #from을 쓴다는건 어딘가에서 가져오는 것
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
y = np.fromfile('t.csv', sep = ',') # 줄 끝의 \n을 읽지 않고 불러오기 때문
y

array([1., 2., 3.])

In [45]:
x = np.array([[1,2,],[4,3]])
x

array([[1, 2],
       [4, 3]])

In [50]:
np.save('tttt',x) #NumPy의 형식으로 저장 -> Pickle 방식

In [53]:
s = np.load('tttt.npy') #loads는 여러파일 읽어오기

In [54]:
s

array([[1, 2],
       [4, 3]])

In [ ]:
np.savez('ttt',x) #여러개의 객체를 묶어(압축) 저장.

- 파이썬은 기본적으로 이 두 파일을 가져올 수 있다.
    - 텍스트 파일 : 사람이 볼 수 있는 형태 -> 어디에서나 열린다.
    - 바이너리 : 각 프로그램이 가지고 있는 고유의 파일

In [55]:
import pickle

In [56]:
with open('sun.ss','wb') as f:
    pickle.dump(s, f)

In [58]:
with open('sun.ss','rb') as f:
    ss = pickle.load(f)

In [59]:
ss

array([[1, 2],
       [4, 3]])

---

In [60]:
a = [1,2,3]

In [61]:
b = a[:] # [:] = copy방식, 스왈로 copy

In [62]:
b[2] = 0

In [63]:
b

[1, 2, 0]

In [64]:
a

[1, 2, 3]

In [66]:
a = [[1,2],3]
b = a[:] #스왈로 copy
b[0][0] = 0

In [67]:
b

[[0, 2], 3]

In [68]:
a

[[0, 2], 3]

In [73]:
a = np.array([[1,2],[3,4]])
b = a[:] # 스왈로 copy
b[0][0]=0

In [74]:
b

array([[0, 2],
       [3, 4]])

In [75]:
a

array([[0, 2],
       [3, 4]])

In [82]:
a = np.array([[1,2],[3,4]])
b = a.view() # 스왈로 copy
b[0][0] = 0
b,a

(array([[0, 2],
        [3, 4]]), array([[0, 2],
        [3, 4]]))