# #003_NumPy

## np.newaxis 

In [8]:
import numpy as np

In [12]:
a = np.array([[11,22],[21,22],[31,32]])

In [13]:
a[np.newaxis]

array([[[11, 22],
        [21, 22],
        [31, 32]]])

In [14]:
a[:,np.newaxis]

array([[[11, 22]],

       [[21, 22]],

       [[31, 32]]])

In [15]:
a[:,:,np.newaxis]

array([[[11],
        [22]],

       [[21],
        [22]],

       [[31],
        [32]]])

---

In [17]:
a = np.array([1,2,3])

In [18]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.tile(a,(2,3)) # == np.tile(a,[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

---

In [21]:
%%writefile t.csv
1,2,3
4,5,6

Writing t.csv


In [28]:
x = np.loadtxt('t.csv', delimiter=',') #delimiter ',' : NumPy가 이해할 수 있게 ,로 이뤄진 것을 알려줌
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
x = np.genfromtxt('t.csv',delimiter=',')
x

array([[1., 2., 3.],
       [4., 5., 6.]])