# #003_NumPy

## np.newaxis 

In [8]:
import numpy as np

In [12]:
a = np.array([[11,22],[21,22],[31,32]])

In [13]:
a[np.newaxis]

array([[[11, 22],
        [21, 22],
        [31, 32]]])

In [14]:
a[:,np.newaxis]

array([[[11, 22]],

       [[21, 22]],

       [[31, 32]]])

In [15]:
a[:,:,np.newaxis]

array([[[11],
        [22]],

       [[21],
        [22]],

       [[31],
        [32]]])

---

In [17]:
a = np.array([1,2,3])

In [18]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.tile(a,(2,3)) # == np.tile(a,[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

---

###  외부 File 읽어오기

In [21]:
%%writefile t.csv
1,2,3
4,5,6

Writing t.csv


In [28]:
x = np.loadtxt('t.csv', delimiter=',') #delimiter ',' : NumPy가 이해할 수 있게 ,로 이뤄진 것을 알려줌
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
x = np.genfromtxt('t.csv',delimiter=',') #from을 쓴다는건 어딘가에서 가져오는 것
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
y = np.fromfile('t.csv', sep = ',') # 줄 끝의 \n을 읽지 않고 불러오기 때문
y

array([1., 2., 3.])

In [36]:
x = np.array([[1,2,],[4,3]])
x

array([[1, 2],
       [4, 3]])

In [38]:
np.savez('x.npz',x) #NumPy의 형식으로 저장

In [41]:
s = np.load('x.npz') #loads는 여러파일 읽어오기

In [42]:
s

- 파이썬은 기본적으로 이 두 파일을 가져올 수 있다.
    - 텍스트 파일 : 사람이 볼 수 있는 형태 -> 어디에서나 열린다.
    - 바이너리 : 각 프로그램이 가지고 있는 고유의 파일