# #002_NumPy 

- Numpy의 Indexing

In [2]:
import numpy as np

In [12]:
a = np.arange(36).reshape(-1,6)

In [13]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [14]:
a[0,3:5]

array([3, 4])

In [15]:
a[4:,4:] # a[[-2:],[-2:]]

array([[28, 29],
       [34, 35]])

In [16]:
a[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [50]:
a[2::2,::2] # ::2는 2개마다

array([[12, 14, 16],
       [24, 26, 28]])

In [38]:
a[[True,False,True,False,True,False]] # Masking기법,[[]]로 가둬야한다.

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [40]:
a[np.ix_([2,4],[0,2,4])]

array([[12, 14, 16],
       [24, 26, 28]])

---

## Named Tuple 

- 시퀀스 타입이면서 딕셔너리처럼 사용할 수 있다

In [41]:
from collections import namedtuple

In [45]:
t = namedtuple('AttendanceSheet',['name','attendance'])

In [46]:
x = t('moon','yes')

In [47]:
x[0]

'moon'

In [48]:
x.name

'moon'

In [49]:
type(x)

__main__.AttendanceSheet

---

## Broadcasting

- 원래 벡터 연산은 서로 모양이 같아야 하지만
- 벡터연산시 상수일때에 한해 벡터의 쉐잎을 맞춰 연산을 해준다.

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a+1 # a+[1,1,1,1,1,1,1,1,1,1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])